#服务器配置
server:
  port: 8090
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

#spring配置
spring:
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  http:
    encoding:
      charset: UTF-8
      force: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    dynamic:
      enabled: false
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      # MySql、PostgreSQL校验
      #validation-query: select 1
      # Oracle校验
      validation-query: select 1 from dual
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: blade
        login-password: 1qaz@WSX
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
      #hikari:
      #connection-test-query: SELECT 1 FROM DUAL
      #connection-timeout: 30000
      #maximum-pool-size: 5
      #max-lifetime: 1800000
      #minimum-idle: 1 
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333

#配置日志地址
logging:
  config: classpath:log/logback_${boot.env}.xml

# mybatis
mybatis-plus:
  mapper-locations: classpath:com/chinasofti/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.chinasofti.**.entity
  jdbc-type-for-null: 'null' 
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
       
#knife4j配置
knife4j:
  #启用
  enable: true
  production: false
  #基础认证
  basic:
    enable: false
    username: blade
    password: blade
  #增强配置
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableHostText: http://127.0.0.1
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh-CN

#swagger配置信息
swagger:
  title: 接口文档系统
  description: 接口文档系统
  version: 1.0.0
  
#boot配置
boot:
  sequence:
    fetch-size: 10
    backend: oracle
  xss:
    enabled: true
    skip-url:
      - /weixin
  secure:
    #skip-url:
    #  - /test/**
    #  - /micro-develop/**
    client:
      - client-id: sword
        path-patterns:
          - /sword/**
      - client-id: saber
        path-patterns:
          - /saber/**
  tenant:
    column: tenant_id
    tables:
      - sys_post
  file:
    allow: xls,xlsx,csv,txt,json
    base: D:\\test\\
